[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "archivio"
  name = "Archivio"
  url = "archivio"
  weight = 2

[[main]]
  identifier = "presentatazione"
  name = "Pt"
  url = "presentazione"
  weight = 3

[[main]]
  identifier = "galleria"
  name = "Galleria"
  url = "galleria"
  weight = 4
    
[[main]]
  parent = "galleria"
  name = "Cartoni"
  url = "gallery/cartoon"

[[main]]
  parent = "galleria"
  name = "Foto"
  url = "gallery/photo"

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 5

[[main]]
  identifier = "showcase"
  name = "Showcase"
  url = "showcase"
  weight = 6

[[main]]
  identifier = "publication"
  name = "Pub"
  url = "publication"
  weight = 7